[project]
name = 'Music-Royalty-Distribution-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.payment-distributor]
path = 'contracts/payment-distributor.clar'
clarity_version = 2
epoch = 2.5

[contracts.revenue-calculator]
path = 'contracts/revenue-calculator.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
